[project]
name = "bat-face-rec-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.8",
    "matplotlib>=3.9.4",
    "mlflow>=3.1.4",
    "opencv-python>=4.8.1.78",
    "pillow>=11.3.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "tensorflow[gpu]==2.15.0",
    "tqdm>=4.67.1",
]
