"""Regenerate ``data/manifests/INDEX.md`` -- what each of the 57 manifests is.

Why
---
The manifest filenames are not self-describing and the inconsistencies are
load-bearing traps: ``mauritius_manifest.csv`` is silently the *random*-background
base arm, and ``*_green_bg`` vs ``*_green_aligned_224`` flip the arm/variant
order. Renaming them would touch 51 configs, ~15 scripts and every doc that
cites a manifest by name, so the names stay frozen and this index decodes them.

Reading goes through ``bat_data.manifest_from_csv``, which verifies each ``.hash``
sidecar, so a successful run doubles as a full integrity check.

Usage
-----
    uv run python scripts/index_data.py            # rewrite data/manifests/INDEX.md
    uv run python scripts/index_data.py --check    # exit 1 if stale (no write)
"""

from __future__ import annotations

import argparse
import collections
import pathlib
import sys

from bat_data import manifest_from_csv

MANIFESTS = pathlib.Path("data/manifests")
CONFIGS = pathlib.Path("configs/data")
INDEX = MANIFESTS / "INDEX.md"

# Manifests with no configs/data/*.yaml. Not dead -- these are read directly by
# the occlusion/silhouette analysis scripts -- so they are flagged, not removed.
ORPHAN_NOTE = "no config; read directly by scripts/"


def configs_for(manifest: pathlib.Path) -> list[str]:
    """Every configs/data/*.yaml whose manifest_path points at this CSV.

    More than one can: the ``*_aligned_112`` and ``*_aligned_224`` configs share
    a single 224px manifest, so returning only the first would hide one of them.
    """
    want = f"data/manifests/{manifest.name}"
    hits = []
    for cfg in sorted(CONFIGS.glob("*.yaml")):
        for line in cfg.read_text(encoding="utf-8").splitlines():
            if line.startswith("manifest_path:") and line.split(":", 1)[1].strip() == want:
                hits.append(cfg.stem.replace("manifest_", ""))
                break
    return hits


def arm_dirs(records) -> list[str]:
    """The variant/arm directories the records live in, relative to the species root."""
    seen = []
    for r in records:
        parts = r.path.parts
        # data/processed/<species>/<source>/<aug>/<variant>/<arm>/<identity>/<file>
        if len(parts) >= 8:
            frag = "/".join(parts[5:7])
            # silhouette/ has no arm level: <variant>/<identity>/<file>
            if len(parts) == 8:
                frag = parts[5]
            if frag not in seen:
                seen.append(frag)
    return seen


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check", action="store_true", help="exit 1 if INDEX.md is stale, write nothing"
    )
    args = ap.parse_args()

    rows = []
    for csv in sorted(MANIFESTS.glob("*.csv")):
        m = manifest_from_csv(csv)  # verifies the .hash sidecar
        splits = collections.Counter(r.split for r in m.records)
        ids = collections.defaultdict(set)
        for r in m.records:
            ids[r.split].add(r.identity)
        cfgs = configs_for(csv)
        rows.append(
            {
                "name": csv.name.replace("_manifest.csv", ""),
                "dirs": arm_dirs(m.records),
                "cfg": cfgs,
                "n": len(m.records),
                "ids": len({r.identity for r in m.records}),
                "split": "/".join(f"{splits.get(s, 0)}" for s in ("train", "val", "test")),
                "split_ids": "/".join(f"{len(ids.get(s, ()))}" for s in ("train", "val", "test")),
                "bg": sorted({r.background for r in m.records})[0],
                "status": "LIVE" if cfgs else "ORPHAN",
            }
        )

    out = []
    out.append("# Manifest index\n")
    out.append(
        "Generated by `scripts/index_data.py` -- **do not hand-edit**, re-run it instead.\n"
        "Regenerating also re-verifies every `.hash` sidecar, so a clean run means\n"
        "all manifests are intact.\n"
    )
    out.append(
        f"\n{len(rows)} manifests. `dir` is relative to\n"
        "`data/processed/<species>/video/not_augmented/`. `imgs` / `ids` are totals;\n"
        "`split` and `split ids` are train/val/test.\n"
    )
    out.append(
        "\n> **Traps.** `mauritius_manifest` / `rousettus_manifest` are the **random**-background\n"
        "> base arm -- the name omits the arm entirely. And `*_green_bg` is `<arm>_bg` while\n"
        "> `*_green_aligned_224` is `<arm>_<variant>`: the two orders are flipped. Read the\n"
        "> `dir` column, not the name.\n"
    )
    out.append("\n| manifest | dir | bg | imgs | ids | split | split ids | config | status |")
    out.append("|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        d = (
            "<br>".join(r["dirs"])
            if len(r["dirs"]) <= 3
            else f"{r['dirs'][0]} … (+{len(r['dirs'])-1})"
        )
        cfg = "<br>".join(f"`{c}`" for c in r["cfg"]) if r["cfg"] else "—"
        out.append(
            f"| `{r['name']}` | `{d}` | {r['bg']} | {r['n']} | {r['ids']} | "
            f"{r['split']} | {r['split_ids']} | {cfg} | {r['status']} |"
        )

    orphans = [r["name"] for r in rows if r["status"] == "ORPHAN"]
    if orphans:
        out.append(f"\n## ORPHAN ({len(orphans)})\n")
        out.append(
            f"{ORPHAN_NOTE} — kept because the analysis in `docs/occlusion_results.md` depends on them.\n"
        )
        for name in orphans:
            out.append(f"- `{name}`")
    out.append("")

    text = "\n".join(out)

    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != text:
            print("INDEX.md is stale — re-run scripts/index_data.py", file=sys.stderr)
            raise SystemExit(1)
        print("INDEX.md up to date")
        return

    INDEX.write_text(text, encoding="utf-8")
    print(f"wrote {INDEX} — {len(rows)} manifests ({len(orphans)} orphan), all hashes verified")


if __name__ == "__main__":
    main()
